export enum RouteComicEnums {
  Home = "/",
  Comics = "/comics",
  Trending = "/trending-comics",
  Genres = "/genres",
  ComicsByGenre = "/genres/:genreId",
  Search = "/search",
  SearchSuggest = "/search-suggest",
  RecommendComics = "/recommend-comics",
  NewComics = "/new-comics",
  BoyComics = "/boy-comics",
  GirlComics = "/girl-comics",
  CompletedComics = "/completed-comics",
  RecentUpdateComics = "/recent-update-comics",
  ComicDetail = "/comics/:comicId",
  Chapters = "/chapters",
  ComicChapters = "/comics/:comicId/chapters",
  SingleChapter = "/comics/:comicId/chapters/:chapterId",
  TopAllComic = "/top",
  TopDailyComic = "/top/daily",
  TopWeeklyComic = "/top/weekly",
  TopMonthlyComic = "/top/monthly",
  TopChapter = "/top/chapter",
  TopFollow = "/top/follow",
  TopComment = "/top/comment",
}
