import { GenreColor } from "../styles/palette";
import { GenreEnums } from "../types/Genres";


const genreToColor: Record<GenreEnums, GenreColor> = {
  [GenreEnums.All]: GenreColor.All,
  [GenreEnums.Action]: GenreColor.Action,
  [GenreEnums.Adult]: GenreColor.Adult,
  [GenreEnums.Adventure]: GenreColor.Adventure,
  [GenreEnums.Anime]: GenreColor.Anime,
  [GenreEnums.ChuyenSinh]: GenreColor.ChuyenSinh,
  [GenreEnums.Comedy]: GenreColor.Comedy,
  [GenreEnums.Comic]: GenreColor.Comic,
  [GenreEnums.Cooking]: GenreColor.Cooking,
  [GenreEnums.CoDai]: GenreColor.CoDai,
  [GenreEnums.Doujinshi]: GenreColor.Doujinshi,
  [GenreEnums.Drama]: GenreColor.Drama,
  [GenreEnums.DamMy]: GenreColor.DamMy,
  [GenreEnums.Ecchi]: GenreColor.Ecchi,
  [GenreEnums.Fantasy]: GenreColor.Fantasy,
  [GenreEnums.GenderBender]: GenreColor.GenderBender,
  [GenreEnums.Harem]: GenreColor.Harem,
  [GenreEnums.Historical]: GenreColor.Historical,
  [GenreEnums.Horror]: GenreColor.Horror,
  [GenreEnums.Josei]: GenreColor.Josei,
  [GenreEnums.LiveAction]: GenreColor.LiveAction,
  [GenreEnums.Manga]: GenreColor.Manga,
  [GenreEnums.Manhua]: GenreColor.Manhua,
  [GenreEnums.Manhwa]: GenreColor.Manhwa,
  [GenreEnums.MartialArts]: GenreColor.MartialArts,
  [GenreEnums.Mature]: GenreColor.Mature,
  [GenreEnums.Mecha]: GenreColor.Mecha,
  [GenreEnums.Mystery]: GenreColor.Mystery,
  [GenreEnums.NgonTinh]: GenreColor.NgonTinh,
  [GenreEnums.OneShot]: GenreColor.OneShot,
  [GenreEnums.Psychological]: GenreColor.Psychological,
  [GenreEnums.Romance]: GenreColor.Romance,
  [GenreEnums.SchoolLife]: GenreColor.SchoolLife,
  [GenreEnums.SciFi]: GenreColor.SciFi,
  [GenreEnums.Seinen]: GenreColor.Seinen,
  [GenreEnums.Shoujo]: GenreColor.Shoujo,
  [GenreEnums.ShoujoAi]: GenreColor.ShoujoAi,
  [GenreEnums.Shounen]: GenreColor.Shounen,
  [GenreEnums.ShounenAi]: GenreColor.ShounenAi,
  [GenreEnums.SliceOfLife]: GenreColor.SliceOfLife,
  [GenreEnums.Smut]: GenreColor.Smut,
  [GenreEnums.SoftYaoi]: GenreColor.SoftYaoi,
  [GenreEnums.SoftYuri]: GenreColor.SoftYuri,
  [GenreEnums.Sports]: GenreColor.Sports,
  [GenreEnums.Supernatural]: GenreColor.Supernatural,
  [GenreEnums.ThieuNhi]: GenreColor.ThieuNhi,
  [GenreEnums.Tragedy]: GenreColor.Tragedy,
  [GenreEnums.TrinhTham]: GenreColor.TrinhTham,
  [GenreEnums.TruyenScan]: GenreColor.TruyenScan,
  [GenreEnums.TruyenMau]: GenreColor.TruyenMau,
  [GenreEnums.Webtoon]: GenreColor.Webtoon,
  [GenreEnums.XuyenKhong]: GenreColor.XuyenKhong,
};

export function getGenreColor(genre: GenreEnums): GenreColor {
  return genreToColor[genre];
}